version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgresdata:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

volumes:
  postgresdata:
    driver: local
  pgadmindata:
    driver: local

networks:
  postgres:
    driver: bridge
